app:
  name: koobeton
  env: dev
  key: GHIOKNmbhjiokjBNMGHJKLmn56789
  listen: ":8000"
  charset: UTF-8
  hostname: http://localhost
  timezone: UTC
  error: debug

db:
  connection: sqlite3
  database: "./conf/koobeton.db"
  #host: mysql
  #port: 3306
  #user: root
  #password: "123456"

mail:
  from: example@example.com
  target: example@example.com
